<h1><center>Laboratorio 3: El Pandas no muerde (act. I) 🐼</center></h1>

<center><strong>MDS7202: Laboratorio de Programación Científica para Ciencia de Datos</strong></center>

---

### Cuerpo Docente

- Profesores: Pablo Badilla y Diego Cortez
- Auxiliares: Valentina Rojas y Melanie Peña
- Ayudantes: Javiera Arévalo, Tamara Carrasco y Ignacio Reyes

### Equipo: SUPER IMPORTANTE - notebooks sin nombre no serán revisados

- Nombre de alumno 1: Javiera Yáñez Sánchez

---

### Reglas

- **Grupos de 2 personas**
- Cualquier duda fuera del horario de clases al foro. Mensajes al equipo docente serán respondidos por este medio.
- Prohibido copiar.
- Uso de LLM (Copilot, Claude, Antigravity, Cursor, etc.) restringido a consultas, documentación y corrección de errores.

### Objetivos

- Entender, aplicar y aprovechar las ventajas que nos ofrece la libreria `pandas` para manejar datos tabulares.
- Aprender a utilizar la documentación de pandas (y en general, de cualquier librería de python) como también a buscar soluciones en la web.

> ⚠️ **Importante**: El laboratorio deberá ser desarrollado sin el uso de iteradores nativos de python (aka "for", "while"). La idea es que aprendan a exprimir al máximo las funciones optimizadas que nos entrega `pandas`.

### Librerias utiles para el Lab 😸

In [1]:
!uv pip install pandas plotly

Using Python 3.14.2 environment at: /Users/javierayanez/Documents/Semestre 11/MDS7202-Laboratorio_Programacion_Cientifica/MDS7202/.venv
Audited 2 packages in 7ms

In [2]:
import pandas as pd
import plotly.express as px

---

# 1. Rendimiento en Estudiantes 📚

### 📊 Sobre los datos

El objetivo principal será realizar un trabajo de limpieza y preparación de datos utilizando exclusivamente DataFrames y las herramientas asociadas a estos. 

Para esto deberán trabajar con el dataset `students_grades.json`, el cual pueden descargar desde la siguiente URL:

> https://raw.githubusercontent.com/MDS7202/MDS7202/refs/heads/main/recursos/2026-01/labs/lab3/students_grades.json

El dataset contiene información sobre el rendimiento de alumnos en distintos ramos. Cada fila representa un estudiante con las siguientes columnas:

- `names`: Nombre del estudiante
- `gender`: Género
- `race/ethnicity`: Grupo étnico
- `parental level of education`: Nivel educacional de los padres
- `lunch`: Tipo de almuerzo (estándar o reducido)
- `test preparation course`: Si completó curso de preparación
- `math score`: Nota de matemáticas (escala 0-100)
- `reading score`: Nota de lectura (escala 0-100)
- `writing score`: Nota de escritura (escala 0-100)


**Nota sobre GPA**: En el contexto educativo anglosajón, GPA (*Grade Point Average*) se refiere al promedio general de calificaciones.

---

## 1.1 Revisión de datos 🔎 [1.2 puntos]

<p align="center">
  <img src="https://media2.giphy.com/media/4FQMuOKR6zQRO/giphy.gif?cid=ecf05e47ii9lhu9tc9tb31d6lafrysp2zyf6u8w3y348mk8t&rid=giphy.gif&ct=g">
</p>

*Don Caguayo*, rector de la Universidad de la Cachaña, les comenta que actualmente la Universidad no tiene una subdirección de análisis de datos, pero que tiene interés en formar una. Es por esto, que se contacta con ud. y su equipo para iniciar de forma exploratoria diversas tareas de análisis y consolidación de datos respectivos al rendimiento de sus alumnos.

En su primera reunión, el rector les comenta que la sección de TI posee una base de datos con más de **1000** filas, en donde cada fila representa un alumno matriculado. Sin embargo, cree fuertemente que existen errores en esta: solo tiene registro de **1000** matriculas. Por este motivo, especula que se han realizado malas prácticas al inscribir dichos datos.


En consecuencia, el rector les solicita a ustedes como tarea inicial que exploren la base de datos y encuentre posibles falencias dentro de sus registros. Para esto, usted debe estar al tanto que las notas (GPA) están en una escala que van del **0 al 100** (porcentaje de logro) y **no es posible que un alumno aparezca más de una vez, ya que las notas son promedios de sus asignaturas**. 

Cualquier alumno que posea un valor diferente a esta escala, debería ser eliminado de la base de datos.

> **Instrucciones**

Implemente la función `analyze_df` que tome un `DataFrame` y que le permita generar diversos análisis que permitan observar estadísticas y anomalías de las diferentes variables que componen este dataset.

**To-Do**
1. [ ] Imprimir un mensaje con las dimensiones del Dataframe. [0.1 puntos]
2. [ ] Imprimir un mensaje con los nombres de las columnas que conforman el DataFrame. [0.1 puntos]
3. [ ] Mostrar los primeros 5, los últimos 5 elementos del DataFrame y realice un muestreo de 5 elementos de forma aleatoria. [0.1 puntos]
4. [ ] Mostrar una descripción rápida de las variables numéricas del DataFrame (utilice un método visto en clases). [0.1 puntos]
5. [ ] Imprimir un mensaje con la cantidad de valores nulos (investigue el método `isna()` y `sum()` de los DataFrames). [0.1 puntos]
6. [ ] Imprimir un mensaje que detalle la cantidad de valores unicos (investigue `nunique()`) . [0.1 puntos]
7. [ ] Imprimir un mensaje con el total de filas que contengan nombres duplicados (investigue `duplicated()` y su parámetro `subset`). [0.1 puntos]
8. [ ] Mostrar las filas que contengan nombres sean duplicados (investigue `duplicated()` y su parámetro `subset`). [0.1 puntos]
9. [ ] A través de `px.histogram(col_name, title="Título").show()` graficar el histograma de cada tipo de nota (`math score`, `reading score`, `writing score`). Investigue cómo funcionan los histogramas si es necesario. [0.2 puntos]
10. [ ] Responda las preguntas en la celda correspondiente. [0.2 puntos]

> **Nota:** Para imprimir utilice `print(...)`. Para mostrar `DataFrames`, utilice `display(...)` ya que este permite mostrar estos elementos como tablas.

> **Nota 2:** Utilice la documentación de [pandas](https://pandas.pydata.org/docs/index.html) como también StackOverflow para resolver cualquier problema o inconveniente.

**Respuesta Código:**

In [3]:
# Primero deberan cargar los datos usando un lector apropiado
df_grades = pd.read_json("students_grades.json")

In [4]:
def analyze_df(df: pd.DataFrame) -> None:
    dimensiones = df.shape
    columnas = df.columns
    primeros_5 = df.head(5)
    ultimos_5 = df.tail(5)
    random_5 = df.sample(5)
    nulos = df.isna().sum()
    unicos = df.nunique().sum()
    duplicados = df.duplicated().sum()
    df_dupli = df[df.duplicated()]
    for col in df.columns:
        try:
            df[col] = pd.to_numeric(df[col], errors="raise")
        except (ValueError, TypeError):
            continue
    descrip_num = df.describe()

    print("Análisis del dataframe")
    print("===" * 5)
    # 1. Imprimir las dimensiones del dataframe
    print(f"Dimensiones (Filas, Columnas): {dimensiones}")
    print("---" * 10)
    # 2. Imprimir los nombres de las columnas
    print(f"\nColumnas presentes: {list(columnas)}")
    print("---" * 10)
    # 3. Imprimir los primeros 5, ultimos 5 y muestre aleatorio de 5.
    print("Primeras 5 filas")
    display(primeros_5)
    print("Últimas 5 filas")
    display(ultimos_5)
    print("Muestra Aleatoria de 5 filas")
    display(random_5)
    # 4. Descripción de los valores numericos
    print("Descripción de Variables Numericas")
    display(descrip_num)
    print("---" * 10)
    # 5. Cantidad de valores nulos
    print("Valores Nulos por Columna:")
    print(nulos)
    print("---" * 10)
    # 6. Cantidad de valores unico
    print(f"Cantidad de valores únicos: {unicos}")
    print("Cantidad de valores únicos por columna:")
    display(df.nunique())
    print("---" * 10)
    # 7. Total de filas con duplicados
    print(f"Cantidad de filas duplicadas: {duplicados}")
    print("---" * 10)
    # 8. Mostrar dataframe de filas duplicadas
    print("Filas duplicadas:")
    display(df_dupli)
    print("---" * 10)

    # 9. Histograma de cada tipo de nota
    col_names = [col for col in df.columns if "score" in col.lower()]
    histograma = px.histogram(df, x=col_names, title="Histograma Notas por Tipo")
    histograma.show()

In [5]:
analyze_df(df_grades)

Análisis del dataframe
===============
Dimensiones (Filas, Columnas): (1400, 9)
------------------------------

Columnas presentes: ['names', 'gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score']
------------------------------
Primeras 5 filas

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,Rita Courtney,female,group B,some high school,standard,none,37,46,46
1,Madeline Fuller,female,group C,some high school,standard,none,124,142,142
2,Daniel Rester,male,group E,associate's degree,standard,none,156,196,193
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80,78,81
4,Geraldine Hale,female,group A,associate's degree,standard,none,131,166,166

Últimas 5 filas

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1395,Alexander Dillon,male,group D,associate's degree,standard,none,193,142,193
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66,74,81
1397,Laurie Carter,female,group B,some high school,standard,completed,54,61,62
1398,Joseph Mccoy,male,group D,some college,free/reduced,none,193,196,193
1399,Amanda Perez,female,group A,high school,standard,completed,68,80,76

Muestra Aleatoria de 5 filas

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
443,Autumn Miller,female,group D,high school,standard,none,196,,193
1170,David Lemke,male,group E,some college,standard,completed,84,83,78
935,Amanda Terrell,female,group A,high school,standard,completed,75,82,79
302,Eileen Parra,female,group B,some high school,free/reduced,none,72,81,79
348,Leona Martinez,female,group D,high school,free/reduced,completed,52,57,56

Descripción de Variables Numericas

        math score  reading score  writing score
count  1360.000000    1360.000000    1353.000000
mean     89.538971      93.086029      91.852919
std      47.152422      46.385775      47.043570
min       0.000000      17.000000      10.000000
25%      59.000000      63.000000      62.000000
50%      72.000000      76.000000      75.000000
75%      97.250000     100.000000     100.000000
max     196.000000     196.000000     196.000000

------------------------------
Valores Nulos por Columna:
names                          0
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64
------------------------------
Cantidad de valores únicos: 1449
Cantidad de valores únicos por columna:

names                          1153
gender                            2
race/ethnicity                    5
parental level of education       6
lunch                             2
test preparation course           2
math score                       96
reading score                    88
writing score                    92
dtype: int64

------------------------------
Cantidad de filas duplicadas: 3
------------------------------
Filas duplicadas:

,names,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
827,Justin Harris,male,group D,some college,standard,none,40,42,38
900,Anthony Malcomb,male,group C,some college,free/reduced,none,35,28,27
1223,Charles Jackson,male,group E,some high school,standard,none,30,26,22

------------------------------

**Preguntas ❓:**

> ¿Qué anomalías es posible observar de los datos que componen el DataFrame? 

> ¿Existen valores nulos o duplicados? ¿Qué puede interpretar de la distribución de las notas en los histogramas?

**Respuestas 📝:**

```
En primera instancia, se puede notar una inconsistencia en el volumen de datos, ya que hay 1400 filas, numero que supera las 1000 matrículas mencionadas inicialmente por el rector. Esto también se puede ver en la columna "names", que solo cuenta con 1157 valores únicos. Al revisar las primeras 5 filas, las últimas 5 filas del dataframe y la muestra aleatoria de 5 filas, se detectan puntajes sobre 100 lo que evidencia una anomalía, posiblemente en el ingreso de datos.

La cantidad de filas duplicadas es 3, lo que no explica la brecha entre los 1400 registros y los 1157 nombres. Esto nos sugiere que existen múltiples registros para un mismo alumno con datos distintos, más que copias idénticas (duplicados) de las filas.

Estadísticamente, el límite inferior de 0 es consistente, pero el superior de 100 es sobrepasado en todas las materias (math, reading y writing), llegando a un máximo de 196. Por otro lado, ninguna columnas tiene valores nulos. Además, se puede notar que hay menos puntajes unicos de "writing score", y, pasado el 75% recién se encuentran los valores atípicos sobre 100 en los puntajes, lo que nos dice que es la minoria de los datos los que vienen con "fallas".

En el histograma, se observa una campana de Gauss normal para los puntajes válidos (dentro del rango 0-100), pero luego aparece un salto que comienza desde los 120 y se extiende hasta 193 en el puntaje. Estos registros fuera de rango representan puntajes no reales y pueden considerarse outliers, ya que se alejan de la distribución de la mayoría de los datos y del límite de la escala de puntaje.
```

---

## 1.2 Limpieza de Datos 🫧

<p align="center">
  <img src="https://media3.giphy.com/media/c09yGbnSyaFRS/giphy.gif?cid=ecf05e47d0ejjjnpfj0ywcbwz7zk7sw2rfdpis890gmdpvj2&rid=giphy.gif&ct=g">
</p>

¡Bien! Ya identificaron las anomalías. Ahora es momento de poner manos a la obra y limpiar esos datos. 🧹

En base a lo realizado anteriormente, realice una limpieza del dataset. Asuma los supuestos señalados en la pregunta anterior para limpiar el DataFrame y cree una función que le permita limpiar los datos. Una vez limpiado, compruebe nuevamente los datos con la función creada en la sección 1.1.

**To-Do:**

- [ ] Crear función que permita limpiar el dataset.
  - [ ] Cambiar el nombre de las columnas a snake case (Hint: implementar util `to_snake_case` usando métodos de strings + list/dict comprehension). [0.1 puntos]
  - [ ] Eliminar la palabra `race` de la columna `race/ethnicity` (Hint: `rename`) [0.1 puntos]
  - [ ] Eliminar datos duplicados [0.2 puntos]
  - [ ] Forzar tipos de las columnas con score a float con `pd.to_numeric, errors="coerce")` (Hint: coerce dejará como nulos los valores que no sean floats, importante para el siguiente paso)[0.2 puntos]
  - [ ] Eliminar datos nulos [0.2 puntos]
  - [ ] Eliminar registros con notas anómalas (> 100, < 0) [0.2 puntos]
- [ ] Comprobar que ya no existen anomalías en los datos usando la función de la sección 1.1 (solo imprimir, no justificar). Puede que necesite adaptar la función para usar los nuevos nombres de columnas

**Respuesta:**

In [6]:
def to_snake_case(s: str) -> str:
    c = s.lower().replace(" ", "_").strip()  # el strip para quitar espacios a los bordes
    return c

In [7]:
def clean_data(df: pd.DataFrame) -> pd.DataFrame:
    # Cambiar nombre de las columnas a snake case
    df.columns = [to_snake_case(col) for col in df.columns]
    # eliminar palabra 'race'
    df.rename(columns={"race/ethnicity": "ethnicity"}, inplace=True)  # inplace cambia original y no una copia
    # eliminar duplicados
    df.drop_duplicates(keep="first", inplace=True)
    # forzar tipo de columna
    col_num_names = ["math_score", "reading_score", "writing_score"]
    for col in col_num_names:
        df.loc[:, col] = pd.to_numeric(df[col], errors="coerce")
    # eliminar nulos
    df = df.dropna(axis=0, how="any")
    # eliminar registro con notas anomalas
    df = df[(df["math_score"] >= 0) & (df["math_score"] <= 100)]
    df = df[(df["reading_score"] >= 0) & (df["reading_score"] <= 100)]
    df = df[(df["writing_score"] >= 0) & (df["writing_score"] <= 100)]

    return df

In [8]:
df_cleaned = clean_data(df_grades)
df_cleaned

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0
...,...,...,...,...,...,...,...,...,...
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

> Utilice la función creada en el punto 1.1 para verificar sus resultados. Adapte los nombres de las columnas con snake_case si es necesario.

In [9]:
analyze_df(df_cleaned)

Análisis del dataframe
===============
Dimensiones (Filas, Columnas): (1000, 9)
------------------------------

Columnas presentes: ['names', 'gender', 'ethnicity', 'parental_level_of_education', 'lunch', 'test_preparation_course', 'math_score', 'reading_score', 'writing_score']
------------------------------
Primeras 5 filas

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0

Últimas 5 filas

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0

Muestra Aleatoria de 5 filas

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
1110,Christopher Thornburg,male,group D,some college,standard,none,60.0,63.0,59.0
389,Gaylene Hunt,female,group D,some college,standard,completed,79.0,84.0,91.0
978,Theodore Sims,male,group B,high school,free/reduced,none,66.0,77.0,70.0
810,Tanya Macinnes,female,group A,some high school,standard,completed,85.0,90.0,92.0
129,Bruce Tang,male,group C,bachelor's degree,standard,none,69.0,63.0,61.0

Descripción de Variables Numericas

       math_score  reading_score  writing_score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

------------------------------
Valores Nulos por Columna:
names                          0
gender                         0
ethnicity                      0
parental_level_of_education    0
lunch                          0
test_preparation_course        0
math_score                     0
reading_score                  0
writing_score                  0
dtype: int64
------------------------------
Cantidad de valores únicos: 1247
Cantidad de valores únicos por columna:

names                          1000
gender                            2
ethnicity                         5
parental_level_of_education       6
lunch                             2
test_preparation_course           2
math_score                       81
reading_score                    72
writing_score                    77
dtype: int64

------------------------------
Cantidad de filas duplicadas: 0
------------------------------
Filas duplicadas:

Empty DataFrame
Columns: [names, gender, ethnicity, parental_level_of_education, lunch, test_preparation_course, math_score, reading_score, writing_score]
Index: []

------------------------------

**✅ Checkpoint**: Después de la limpieza deberías tener exactamente 1000 filas

---

## 1.3 Creando y Estructurando Datos 📊



<p align="center">
  <img src="https://media4.giphy.com/media/ko7twHhomhk8E/giphy.gif?cid=ecf05e47xmgfz8ftaom8saa4cwktxpb0fkui9yk3nakb4ff1&rid=giphy.gif&ct=g">
</p>

¡Perfecto! Ya tenemos datos limpios y confiables. Ahora Don Caguayo quiere que le ayudemos a generar nuevas columnas y realizar análisis más profundos. 📊

---

### 1.3.1 Transformación de notas a "Nota Chilena" 🇨🇱 [0.5 puntos]

En una de las reuniones con Don Caguayo, este les comenta su intención de pasar todas sus notas a la "Escala Chilena". Para esto les facilita la siguiente ecuación:

$$Nota \, Chilena= \% \, de \, logro \times 0.06 + 1$$

Utilizando la ecuación entregada, cree una función que le permita transformar las notas (que están en escala 0-100) a la escala chilena [1,7] y entregue las notas redondeadas al segundo decimal.

**To-Do**

- [ ] Implementa la función `to_chilean_grade` que toma un **DataFrame** y el nombre de una **columna** con notas en escala 0-100, y retorna una **Serie** con las notas transformadas a escala chilena (rango 1.0-7.0). [0.3 puntos]
- [ ] Agrega las nuevas series de notas de matemáticas (columna `math_score_cl`), lectura (columna `reading_score_cl`) y escritura (columna `writing_score_cl`) al dataframe `df_cleaned`. [0.3 puntos]

**Respuesta Código:**

In [10]:
# En esta celda implementa la operación solicitada
def to_chilean_grade(df: pd.DataFrame, columna: str) -> tuple[pd.Series, pd.Series]:
    nota = df.loc[:, columna]
    nota_cl = (nota * 0.06 + 1).round(2)
    return nota, nota_cl

In [11]:
# En esta celda ejecuta la función y luego usa indexadores para agregar las nuevas columnas al dataframe limpio
nota_math, nota_math_cl = to_chilean_grade(df_cleaned, "math_score")
nota_reading, nota_reading_cl = to_chilean_grade(df_cleaned, "reading_score")
nota_writing, nota_writing_cl = to_chilean_grade(df_cleaned, "writing_score")

df_cleaned.loc[:, "math_score_cl"] = nota_math_cl
df_cleaned.loc[:, "reading_score_cl"] = nota_reading_cl
df_cleaned.loc[:, "writing_score_cl"] = nota_writing_cl

---

### 1.3.2 Promedios 📋 [0.3 puntos]

Con todas las notas transformadas, la prestigiosa Universidad De la Cachaña necesita obtener el promedio general (GPA) de cada uno de los alumnos. Para esto se le solicita que calcule el promedio de las tres asignaturas y lo anexe como una nueva columna al DataFrame. 

Cabe señalar que las notas promedio deben ser **redondeadas** al segundo decimal.

**To-Do:**
- [ ] Implementa la función `calculate_average` que dado un dataframe con las notas por alumno, calcula y retorna dos **Series**: una con el promedio de las notas originales (escala 0-100) y otra con el promedio de las notas chilenas.
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega las columnas `mean` (promedio escala 0-100) y `mean_cl` (promedio escala chilena) a `df_cleaned`.

**Respuesta:**

In [12]:
# En esta celda implementa la operación solicitada
def calculate_average(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    cols_orig = ["math_score", "reading_score", "writing_score"]
    cols_cl = ["math_score_cl", "reading_score_cl", "writing_score_cl"]

    mean_score = df.loc[:, cols_orig].mean(axis=1).round(2)
    mean_score_cl = df.loc[:, cols_cl].mean(axis=1).round(2)

    return mean_score, mean_score_cl

In [13]:
# En esta celda ejecuta la función y luego usa indexadores para agregar la nueva columna al dataframe limpio
mean, mean_cl = calculate_average(df_cleaned)

df_cleaned.loc[:, "mean"] = mean
df_cleaned.loc[:, "mean_cl"] = mean_cl

---

### 1.3.3 Rankings 📶 [0.4 puntos]

¡Excelente trabajo calculando los promedios! Ahora Don Caguayo quiere saber quiénes son los estudiantes top y generar un ranking general.

**To-Do:**
- [ ] Implementa la función `rank_students` que dado un dataframe con las notas por alumno, obtiene una **Serie** con el ranking de alumnos, de mejor a peor nota (usando el promedio chileno `mean_cl`).
- [ ] Ejecuta la función y luego, usando indexadores apropiados, agrega la columna `rank` al `df_cleaned`.

In [14]:
# En esta celda implementa la operación solicitada
def rank_students(df: pd.DataFrame) -> pd.Series:
    rank = df.loc[:, "mean_cl"].rank(ascending=False)
    return rank

In [15]:
# En esta celda ejecuta la función y luego usa indexadores para agregar la nueva columna al dataframe limpio
rank = rank_students(df_cleaned)
df_cleaned.loc[:, "rank"] = rank

In [16]:
df_cleaned

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl,mean,mean_cl,rank
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.22,3.76,3.76,43.00,3.58,960.5
3,Charles Linstrom,male,group A,bachelor's degree,standard,completed,80.0,78.0,81.0,5.80,5.68,5.86,79.67,5.78,202.5
5,Brian Young,male,group C,some high school,standard,none,73.0,66.0,63.0,5.38,4.96,4.78,67.33,5.04,536.5
6,Howard Jimenez,male,group E,some high school,standard,completed,81.0,75.0,76.0,5.86,5.50,5.56,77.33,5.64,261.5
7,Wayne Wilson,male,group B,some high school,standard,completed,94.0,86.0,87.0,6.64,6.16,6.22,89.00,6.34,61.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1392,Richard Young,male,group D,high school,standard,none,69.0,75.0,71.0,5.14,5.50,5.26,71.67,5.30,407.5
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0,2.38,3.64,3.16,34.33,3.06,985.0
1396,Marina Zeigler,female,group C,bachelor's degree,free/reduced,completed,66.0,74.0,81.0,4.96,5.44,5.86,73.67,5.42,353.0
1397,Laurie Carter,female,group B,some high school,standard,completed,54.0,61.0,62.0,4.24,4.66,4.72,59.00,4.54,731.0
1399,Amanda Perez,female,group A,high school,standard,completed,68.0,80.0,76.0,5.08,5.80,5.56,74.67,5.48,328.5

**Preguntas ❓:**


1. ¿Qué pasa si hay alumnos con el mismo promedio? 
2. ¿Cómo se debería manejar el ranking en ese caso? 
3. ¿Qué parámetro deberían configurar? 
 
4. ¿Cuál es el comportamiento por defecto?

**Respuestas 📝:**

```
Cuando hay alumnos con el mismo promedio, la función ranking, como no sabe a quién poner primero, hace un promedio. Por ejemplo: dos alumnos quedan empatados en el primer lugar por tener la misma media; deberían ocupar dos posiciones, 1 y 2; por lo tanto, el promedio del puesto sería 1.5 y ambos quedarían con ese valor. Siendo este su comportamiento por defecto, correspondiente a "method = 'average'".

Para manejar el ranking, en ese caso se puede dejar expresado de esa manera o se podría dejar como número entero, con el parámetro "method = 'min'"; las posiciones dejan de ser decimales y, en caso de que empaten uno o varios estudiantes con un mismo lugar, por ejemplo la posición 1, todos quedan con ese ranking asociado; sin embargo, el alumno que viene quedaría con el puesto 3. Para evitar lo anterior, y que el alumno que siga quede con la posición 2, se puede utilizar "method='dense'". Existen otras formas también, como el método 'first', que asigna al empate los valores correspondientes del orden; como el ejemplo que vimos, asignaría 1 y 2; o el método 'max', que al empate les asigna el puesto siguiente (si hay empate en el 1, a ambos les asigna 2). ``

---

### 1.3.4 Reprobados y Destacados 🏅

Contentos con su desempeño, la Universidad les solicita que identifiquen a los alumnos que han reprobado el año y a los que han tenido un desempeño destacado.

Para esto se considerará que:
- Un alumno ha **reprobado** cuando el promedio de notas chilenas (`mean_cl`) es inferior a 4.0
- Un alumno es **destacado** si posee notas chilenas superiores a 6.0 en `math_score_cl` y superiores a 6.3 en `reading_score_cl` y `writing_score_cl`


Cree las siguientes funciones:

1. [ ] `extract_failing` que retorne un DataFrame con solamente los alumnos que han reprobado en la prestigiosa universidad. [0.3 puntos]
2. [ ]  `sort_top` que extraiga los n (parametrizable) alumnos destacados, ordenados de mayor a menor promedio. [0.3 puntos]

**Respuesta:**

In [17]:
def extract_failing(df: pd.DataFrame) -> pd.DataFrame:
    df_reprobados = df.loc[df["mean_cl"] < 4.0]
    return df_reprobados


df_failing = extract_failing(df_cleaned)

In [18]:
df_failing

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl,mean,mean_cl,rank
0,Rita Courtney,female,group B,some high school,standard,none,37.0,46.0,46.0,3.22,3.76,3.76,43.00,3.58,960.5
13,Mikki Amaya,female,group A,high school,free/reduced,completed,34.0,48.0,41.0,3.04,3.88,3.46,41.00,3.46,965.5
26,Samuel Dougal,male,group C,master's degree,free/reduced,completed,46.0,42.0,46.0,3.76,3.52,3.76,44.67,3.68,948.5
55,Rodger Talavera,male,group B,high school,free/reduced,none,36.0,29.0,27.0,3.16,2.74,2.62,30.67,2.84,990.0
63,Morris Johnson,male,group A,associate's degree,free/reduced,completed,40.0,55.0,53.0,3.40,4.30,4.18,49.33,3.96,902.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1371,Charles Harian,male,group C,some high school,free/reduced,completed,45.0,52.0,49.0,3.70,4.12,3.94,48.67,3.92,912.5
1373,Wendy Gunnell,female,group D,some high school,free/reduced,none,27.0,34.0,32.0,2.62,3.04,2.92,31.00,2.86,989.0
1389,Diana Costa,female,group C,high school,free/reduced,none,41.0,46.0,43.0,3.46,3.76,3.58,43.33,3.60,957.5
1391,Amy Sieving,female,group C,high school,standard,none,29.0,29.0,30.0,2.74,2.74,2.80,29.33,2.76,994.0
1394,Wanda Russell,female,group B,high school,free/reduced,completed,23.0,44.0,36.0,2.38,3.64,3.16,34.33,3.06,985.0

In [19]:
def sort_top(df: pd.DataFrame, n: int) -> pd.DataFrame:
    df_top = df.loc[(df["math_score_cl"] > 6.0) & (df["reading_score_cl"] > 6.3) & (df["writing_score_cl"] > 6.3)]
    df_top_n = df_top.sort_values(by="mean_cl", ascending=False).head(n)

    return df_top_n


df_top_students = sort_top(df_cleaned, n=10)

In [20]:
df_top_students

,names,gender,ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score,math_score_cl,reading_score_cl,writing_score_cl,mean,mean_cl,rank
677,Richard Pryor,male,group E,bachelor's degree,standard,completed,100.0,100.0,100.0,7.00,7.00,7.00,100.00,7.00,2.0
384,Elizabeth Beasley,female,group E,bachelor's degree,standard,none,100.0,100.0,100.0,7.00,7.00,7.00,100.00,7.00,2.0
1352,Sandra Pompey,female,group E,associate's degree,standard,none,100.0,100.0,100.0,7.00,7.00,7.00,100.00,7.00,2.0
475,Emma Gray,female,group E,bachelor's degree,standard,completed,99.0,100.0,100.0,6.94,7.00,7.00,99.67,6.98,4.0
1276,Angela Cressey,female,group D,some college,standard,none,98.0,100.0,99.0,6.88,7.00,6.94,99.00,6.94,5.5
279,Emma Brasher,female,group D,some high school,standard,completed,97.0,100.0,100.0,6.82,7.00,7.00,99.00,6.94,5.5
1381,Robert Morrison,male,group D,some college,standard,completed,100.0,97.0,99.0,7.00,6.82,6.94,98.67,6.92,7.5
1219,Emmie Mooreland,female,group C,bachelor's degree,standard,completed,96.0,100.0,100.0,6.76,7.00,7.00,98.67,6.92,7.5
514,David Martinez,male,group E,associate's degree,free/reduced,completed,100.0,100.0,93.0,7.00,7.00,6.58,97.67,6.86,10.0
35,Shanna Braswell,female,group D,bachelor's degree,free/reduced,completed,93.0,100.0,100.0,6.58,7.00,7.00,97.67,6.86,10.0

---

### 1.3.5 Padres Helicóptero 👨‍👩‍👧

Algunos padres (extremadamente entrometidos) preocupados por el desempeño de sus hijos, desean saber si estos han aprobado o no el año. Como la tarea de buscar a mano cada uno de estos alumnos en el `DataFrame` resulta demasiado tedioso, el rector le solicita crear una función de consulta. 

Cree una función que:

1. Reciba el `DataFrame` y una lista con nombres de alumnos
2. Extraiga las notas chilenas de matemáticas, escritura, lectura y promedio general (`mean_cl`) de los alumnos listados en `student_list` [0.3 puntos]
3. Genere una nueva columna transitoria `is_failing` (**asegurarse de no agregarla al dataframe original**) cuyo valor sea `True` si el alumno está reprobando o `False` en caso contrario [0.3 puntos]
4. Ordene por promedio chileno, de mayor a menor [0.2 puntos]
5. Reinicie el índice para que este comience desde 0 [0.2 puntos]


**Hint:** Puede serle de utilidad utilizar `isin()`. Recuerde además usar una copia del dataframe original para no modificarlo con la nueva columna.

**Respuesta:**

In [21]:
def query_students(df: pd.DataFrame, student_list: list[str]) -> pd.DataFrame:
    df_copy = df.copy()
    df_copy = df_copy.loc[df_copy["names"].isin(student_list)]  # seleccionamos solo los estudiantes de la lista
    cols_cl = ["names", "math_score_cl", "reading_score_cl", "writing_score_cl", "mean_cl"]
    df_copy = df_copy.loc[:, cols_cl]  # seleccionamos solo las columnas que piden
    df_copy.loc[:, "is_failing"] = df_copy["mean_cl"] < 4.0  # booleano
    df_copy = df_copy.sort_values(by="mean_cl", ascending=False)
    df_copy = df_copy.reset_index(drop=True)

    return df_copy

In [22]:
student_list = [
    "Lucille Stanphill",
    "Marcus Mcfarland",
    "Matthew Freeman",
    "Dana Mojica",
    "Paul Hyder",
    "Jeffrey Korn",
    "Robert Strain",
    "Ronald Jett",
    "Lorena Reed",
    "Hazel Posey",
]

df_query = query_students(df_cleaned, student_list)
df_query

,names,math_score_cl,reading_score_cl,writing_score_cl,mean_cl,is_failing
0,Paul Hyder,6.70,5.86,6.04,6.20,False
1,Lucille Stanphill,5.86,6.04,5.92,5.94,False
2,Marcus Mcfarland,4.78,4.84,4.96,4.86,False
3,Jeffrey Korn,5.20,4.36,4.06,4.54,False
4,Robert Strain,4.30,4.66,4.24,4.40,False
5,Matthew Freeman,4.12,3.94,3.76,3.94,True
6,Dana Mojica,3.34,4.12,3.76,3.74,True
7,Lorena Reed,3.16,4.18,3.58,3.64,True
8,Ronald Jett,3.52,3.34,3.04,3.30,True
9,Hazel Posey,2.44,3.28,2.62,2.78,True

---

### 1.3.6 Categorías de Rendimiento 📊

El rector, intrigado por saber si existe una relación entre el nivel educacional de los padres y las notas de sus hijos, les plantea estudiar dicha relación mediante categorización de los datos. 

Para esto, se les solicita que implementen la función `get_categories`, donde se generen dos series con diferentes tipos de categorización a partir de los promedios chilenos (`mean_cl`):

- Una con `pd.cut` con las labels `["B1", "B2", "B3", "B4", "B5"]` [0.2 Puntos]
- Otra con `pd.qcut`, con las labels `["Q1", "Q2", "Q3", "Q4", "Q5"]` [0.2 Puntos]

La función debe retornar una tupla con ambas series. Después, usando indexadores apropiados, agreguen a `df_cleaned` las columnas `cut_cl` y `qcut_cl`.

**Respuesta:**

In [23]:
# En esta celda implementa la operación solicitada
def get_categories(df: pd.DataFrame) -> tuple[pd.Series, pd.Series]:
    labels_cut = ["B1", "B2", "B3", "B4", "B5"]
    labels_qcut = ["Q1", "Q2", "Q3", "Q4", "Q5"]
    cut_cl = pd.cut(df["mean_cl"], bins=5, labels=labels_cut)
    qcut_cl = pd.qcut(df["mean_cl"], q=5, labels=labels_qcut)

    return cut_cl, qcut_cl

In [24]:
# indexadores
cut_cl, qcut_cl = get_categories(df_cleaned)

df_cleaned.loc[:, "cut_cl"] = cut_cl
df_cleaned.loc[:, "qcut_cl"] = qcut_cl

Hecho esto, grafique a través de un scatter plot el nivel educacional de los padres v/s el promedio chileno de los alumnos. Utilice los quintiles generados anteriormente (use la columna `qcut_cl`) para colorear los puntos y mostrar en qué quintil se encuentra cada dato.

**Pregunta: ❓** [0.3 Puntos]

> - ¿Qué diferencias hay entre las categorías generadas por `cut` y `qcut` (en términos conceptuales rangos-percentiles)?

**Respuesta 📝:**

```
La categoría 'cut' divide el rango del promedio de notas (1 al 7) en 5 intervalos, sin tomar la cantidad de estudiantes, sino solo sus notas. En cambio, qcut divide en cuantiles, es decir, para este caso toma el 20% de los alumnos (ordenados de menor a mayor) y le asigna el primer quintil y así sucesivamente; ordenando los alumnos por nota pero fijando los intervalos por posición. Es por esto que los grupos generados por qcut están balanceados en cantidad de datos, aunque los rangos de notas tengan "anchos" distintos.
```

In [25]:
# Código para graficar
# Nota: asegúrese de que la columna qcut_cl esté creada antes de ejecutar esto

fig = px.scatter(
    df_cleaned.sort_values(by="mean_cl"),
    x="mean_cl",
    y="parental_level_of_education",
    hover_data=["gender"],
    color="qcut_cl",
    title="Promedio por Nivel de Educación de los Padres",
    labels={"mean_cl": "Promedio (Escala Chilena)", "parental_level_of_education": "Nivel Educacional de los Padres"},
    color_discrete_sequence=["tomato", "orange", "yellow", "greenyellow", "green"],
)
fig.show()

**Pregunta: ❓** [0.3 Puntos]

> - ¿Es posible visualizar alguna tendencia en el gráfico?

**Respuesta 📝:**

```
Se puede observar una clara tendencia. Se puede observar que, a medida que el nivel educacional de los padres aumenta (masters, bachelors), los puntos se desplazan hacia la derecha y aumenta la densidad en los quintiles superiores (Q4 y Q5). Por el contrario, a niveles educacionales más bajos, los puntos se desplazan a la izquierda con mayor presencia en los quintiles bajos (Q1 y Q2). Por lo que se podría concluir a grandes rasgos que existe una correlación positiva entre el nivel educacional de los padres y el rendimiento de los hijos en este dataset.
```

---

# Conclusión

Cualquier duda del laboratorio, no duden en contactarnos por mail o U-cursos.

<p align="center">
  <img src="https://gifdb.com/images/high/orange-cat-cat-walking-with-two-legs-xlgf7qx4i24da74f.gif" width="400">
</p>